spring.application.name=tfg

# Configuración de la base de datos
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configuración para ejecutar los scripts schema.sql y data.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
