logging:
  level:
    org:
      hibernate:
        SQL: debug

spring:
  sql:  
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    # Configuración para H2 en memoria
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false

  jackson:
    default-property-inclusion: NON_NULL

  jpa:
    hibernate:
      ddl-auto: update  # 'create', 'update', 'validate' o 'none'
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    context-path: ${project.contextPath}

project:
  jwt:
    signKey: WzROun12eUiDvko3UrJ74gNeJz2TWEWPMTh6DxyE8HWXIf4hETUrkM4IUGqqHq66PuVS
    expirationMinutes: 1440
  contextPath: /tfg  # Aquí defines tu ruta de contexto
