CREATE TABLE IF NOT EXISTS Users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    userName VARCHAR(60) NOT NULL,
    password VARCHAR(60) NOT NULL, 
    email VARCHAR(60) NOT NULL, 
    avatar VARCHAR(255) NOT NULL,
    role TINYINT NOT NULL,
    CONSTRAINT UserPK PRIMARY KEY (id),
    CONSTRAINT UserNameUniqueKey UNIQUE (userName),
    CONSTRAINT EmailUniqueKey UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Movies (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imdbId VARCHAR(60) NOT NULL,
    title VARCHAR(255) NOT NULL,
    overview TEXT,
    releaseYear INT,
    verticalPoster VARCHAR(600),
    runtime INT,
    CONSTRAINT MoviePK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Genres (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT GenrePK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Actors (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imdbId VARCHAR(60),
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    birthDate DATE,
    birthPlace VARCHAR(255),
    starSign VARCHAR(50),
    height VARCHAR(50),
    bio TEXT,
    imageUrl VARCHAR(600),
    CONSTRAINT ActorPK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Directors (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    CONSTRAINT DirectorPK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CustomLists (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    userId BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT CustomListPK PRIMARY KEY (id),
    CONSTRAINT FK_CustomList_User FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS CustomListMovies (
    listId BIGINT NOT NULL,
    movieId BIGINT NOT NULL,
    CONSTRAINT CustomListMoviePK PRIMARY KEY (listId, movieId),
    CONSTRAINT FK_CustomListMovie_List FOREIGN KEY (listId) REFERENCES CustomLists(id),
    CONSTRAINT FK_CustomListMovie_Movie FOREIGN KEY (movieId) REFERENCES Movies(id)
);

CREATE TABLE IF NOT EXISTS MovieGenres (
    movieId BIGINT NOT NULL,
    genreId BIGINT NOT NULL,
    CONSTRAINT MovieGenrePK PRIMARY KEY (movieId, genreId),
    CONSTRAINT FK_MovieGenre_Movie FOREIGN KEY (movieId) REFERENCES Movies(id),
    CONSTRAINT FK_MovieGenre_Genre FOREIGN KEY (genreId) REFERENCES Genres(id)
);

CREATE TABLE IF NOT EXISTS MovieActors (
    movieId BIGINT NOT NULL,
    actorId BIGINT NOT NULL,
    CONSTRAINT MovieActorPK PRIMARY KEY (movieId, actorId),
    CONSTRAINT FK_MovieActor_Movie FOREIGN KEY (movieId) REFERENCES Movies(id),
    CONSTRAINT FK_MovieActor_Actor FOREIGN KEY (actorId) REFERENCES Actors(id)
);

CREATE TABLE IF NOT EXISTS MovieDirectors (
    movieId BIGINT NOT NULL,
    directorId BIGINT NOT NULL,
    CONSTRAINT MovieDirectorPK PRIMARY KEY (movieId, directorId),
    CONSTRAINT FK_MovieDirector_Movie FOREIGN KEY (movieId) REFERENCES Movies(id),
    CONSTRAINT FK_MovieDirector_Director FOREIGN KEY (directorId) REFERENCES Directors(id)
);