CREATE TABLE IF NOT EXISTS Users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    userName VARCHAR(60) NOT NULL,
    password VARCHAR(60) NOT NULL, 
    email VARCHAR(60) NOT NULL, 
    avatar VARCHAR(255) NOT NULL,
    role TINYINT NOT NULL,
    CONSTRAINT UserPK PRIMARY KEY (id),
    CONSTRAINT UserNameUniqueKey UNIQUE (userName),
    CONSTRAINT EmailUniqueKey UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Movies (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imdbId VARCHAR(60) NOT NULL,
    title VARCHAR(255) NOT NULL,
    overview TEXT,
    releaseYear INT,
    verticalPoster VARCHAR(600),
    runtime INT,
    CONSTRAINT MoviePK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Genres (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT GenrePK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Actors (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imdbId VARCHAR(60),
    name VARCHAR(255) NOT NULL,
    birthDate DATE,
    birthPlace VARCHAR(255),
    starSign VARCHAR(50),
    height VARCHAR(50),
    bio TEXT,
    imageUrl VARCHAR(600),
    CONSTRAINT ActorPK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Directors (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imdbId VARCHAR(60),
    name VARCHAR(255) NOT NULL,
    birthDate DATE,
    birthPlace VARCHAR(255),
    starSign VARCHAR(50),
    height VARCHAR(50),
    bio TEXT,
    imageUrl VARCHAR(600),
    CONSTRAINT DirectorPK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CustomLists (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    userId BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT CustomListPK PRIMARY KEY (id),
    CONSTRAINT FK_CustomList_User FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS CustomListMovies (
    listId BIGINT NOT NULL,
    movieId BIGINT NOT NULL,
    CONSTRAINT CustomListMoviePK PRIMARY KEY (listId, movieId),
    CONSTRAINT FK_CustomListMovie_List FOREIGN KEY (listId) REFERENCES CustomLists(id),
    CONSTRAINT FK_CustomListMovie_Movie FOREIGN KEY (movieId) REFERENCES Movies(id)
);

CREATE TABLE IF NOT EXISTS ActorLists (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    userId BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT ActorListPK PRIMARY KEY (id),
    CONSTRAINT FK_ActorList_User FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS ActorListItems (
    listId BIGINT NOT NULL,
    actorId BIGINT NOT NULL,
    CONSTRAINT ActorListItemPK PRIMARY KEY (listId, actorId),
    CONSTRAINT FK_ActorListItem_List FOREIGN KEY (listId) REFERENCES ActorLists(id),
    CONSTRAINT FK_ActorListItem_Actor FOREIGN KEY (actorId) REFERENCES Actors(id)
);

CREATE TABLE IF NOT EXISTS DirectorLists (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    userId BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT DirectorListPK PRIMARY KEY (id),
    CONSTRAINT FK_DirectorList_User FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS DirectorListItems (
    listId BIGINT NOT NULL,
    directorId BIGINT NOT NULL,
    CONSTRAINT DirectorListItemPK PRIMARY KEY (listId, directorId),
    CONSTRAINT FK_DirectorListItem_List FOREIGN KEY (listId) REFERENCES DirectorLists(id),
    CONSTRAINT FK_DirectorListItem_Director FOREIGN KEY (directorId) REFERENCES Directors(id)
);

CREATE TABLE IF NOT EXISTS MovieGenres (
    movieId BIGINT NOT NULL,
    genreId BIGINT NOT NULL,
    CONSTRAINT MovieGenrePK PRIMARY KEY (movieId, genreId),
    CONSTRAINT FK_MovieGenre_Movie FOREIGN KEY (movieId) REFERENCES Movies(id),
    CONSTRAINT FK_MovieGenre_Genre FOREIGN KEY (genreId) REFERENCES Genres(id)
);

CREATE TABLE IF NOT EXISTS MovieActors (
    movieId BIGINT NOT NULL,
    actorId BIGINT NOT NULL,
    CONSTRAINT MovieActorPK PRIMARY KEY (movieId, actorId),
    CONSTRAINT FK_MovieActor_Movie FOREIGN KEY (movieId) REFERENCES Movies(id),
    CONSTRAINT FK_MovieActor_Actor FOREIGN KEY (actorId) REFERENCES Actors(id)
);

CREATE TABLE IF NOT EXISTS MovieDirectors (
    movieId BIGINT NOT NULL,
    directorId BIGINT NOT NULL,
    CONSTRAINT MovieDirectorPK PRIMARY KEY (movieId, directorId),
    CONSTRAINT FK_MovieDirector_Movie FOREIGN KEY (movieId) REFERENCES Movies(id),
    CONSTRAINT FK_MovieDirector_Director FOREIGN KEY (directorId) REFERENCES Directors(id)
);

CREATE TABLE IF NOT EXISTS MovieRatings (
    userId BIGINT NOT NULL,
    movieId BIGINT NOT NULL,
    rating INT NOT NULL,
    CONSTRAINT RatingValueCheck CHECK (rating >= 0 AND rating <= 10),
    CONSTRAINT MovieRatingPK PRIMARY KEY (userId, movieId),
    CONSTRAINT FK_MovieRating_User FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT FK_MovieRating_Movie FOREIGN KEY (movieId) REFERENCES Movies(id)
);